name: Create Tag

on:
  push:
    branches:
      - master

jobs:
  create-tag:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: '${{ secrets.USER_TOKEN }}'
    steps:
      - uses: actions/checkout@v2

      - name: 'Create main tag'
        id: 'main'
        uses: butlerlogic/action-autotag@1.1.2
        with:
          tag_prefix: 'x-v'

      - name: 'Create latest tag'
        if: ${{ contains(steps.main.outputs.tagname, 'v') }}
        uses: EndBug/latest-tag@latest

      - name: 'Create js tag'
        uses: butlerlogic/action-autotag@1.1.2
        with:
          root: '/packages/embeds/js'
          tag_prefix: 'x-js-v'

      - name: 'Create react tag'
        uses: butlerlogic/action-autotag@1.1.2
        with:
          root: '/packages/embeds/react'
          tag_prefix: 'x-react-v'

      - name: 'Create nextjs tag'
        uses: butlerlogic/action-autotag@1.1.2
        with:
          root: '/packages/embeds/nextjs'
          tag_prefix: 'x-nextjs-v'
